# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "win10-reversing" do |cfg|
    cfg.vm.box = "cyberdefenders/win10"
    cfg.vm.hostname = "reversing"
    cfg.vm.boot_timeout = 1200
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = false
    cfg.winrm.timeout = 1200
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.104", gateway: "192.168.38.1", dns: "192.168.38.102"
  
    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.38.104 -dns 8.8.8.8 -gateway 192.168.38.1" 
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/download_palantir_wef.ps1", privileged: false
    cfg.vm.provision "shell", inline: 'wevtutil el | Select-String -notmatch "Microsoft-Windows-LiveId" | Foreach-Object {wevtutil cl "$_"}', privileged: false
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-choco-extras.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: false
    # cfg.vm.provision "shell", path: "scripts/install-windbg.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-x64dbg.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-processhacker.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-pebear.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-010editor.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-dnSpy.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-ida-free.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-ghidra.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-yara.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-detectiteasy.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-pestudio.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-pywin32.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/install-burpfree.ps1", privileged: false
    # cfg.vm.provision "enable-public-winrm", type: "shell", path: "scripts/enable-winrm.ps1", privileged: false
    cfg.vm.provision "shell", inline: 'cscript c:\windows\system32\slmgr.vbs /dlv', privileged: false
  
    cfg.vm.provider "vmware_desktop" do |v, override|
     v.vmx["displayname"] = "win10-reversing"
     v.vmx["gui.fullscreenatpoweron"] = "FALSE"
     v.vmx["gui.viewModeAtPowerOn"] = "windowed"
     v.memory = 2048
     v.cpus = 1
     v.gui = true
     v.enable_vmrun_ip_lookup = false
    end
  
    cfg.vm.provider "virtualbox" do |vb, override|
     vb.gui = false
     vb.name = "win10-reversing"
     vb.default_nic_type = "82545EM"
     vb.customize ["modifyvm", :id, "--ostype", "Windows10_64"]
     vb.customize ["modifyvm", :id, "--memory", 2048]
     vb.customize ["modifyvm", :id, "--cpus", 2]
     vb.customize ["modifyvm", :id, "--vram", "32"]
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
